name: build

on: [ push, pull_request ]

jobs:
  wrapper:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Gradle Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17
    - name: Build Game Wrapper
      run: cd wrapper && ./gradlew --no-daemon build && cd ..
    - name: Upload Artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: Wrapper
        path: wrapper/build/libs/sol-client-wrapper.jar
    
  upload:
    if: "github.ref == 'refs/heads/stable' && startsWith(github.event.head_commit.message, '[create release] ')"

    runs-on: ubuntu-latest
  
    needs: wrapper
    
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Download Artifacts
      uses: actions/download-artifact@v2

    # https://stackoverflow.com/a/61919791
    - name: Retrieve Version
      run: cat version.txt
      id: version

    - name: Create a Release
      uses: marvinpinto/action-automatic-releases@latest
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ fromJson(steps.version.outputs.packageJson).version }}
        prerelease: false
        title: ${{ fromJson(steps.version.outputs.packageJson).version }}
        files: |
          Sol-Client-Launcher-Linux/deb/x64/*.deb
          Sol-Client-Launcher-Linux/*.AppImage
          Sol-Client-Launcher-Windows/*.exe
          Sol-Client-Launcher-MacOS/*.dmg
          Wrapper/sol-client-wrapper.jar
